## FOSHttpCache Configuration
fos_http_cache:
    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/user-context.html#configuration
    user_context:
        # As of eZ Platform v3.2 we ship with this disabled by default for better cache efficiency (EZP-28916).
        # UPGRADE NOTE: For upgrades you might want to omit it, as it implies *all* custom controllers
        #               that relies on user rights needs an explicit: $response->setVary('X-User-Context-Hash');
        always_vary_on_context_hash: false

    # https://foshttpcachebundle.readthedocs.io/en/latest/reference/configuration/headers.html
    cache_control:
        rules:
            # Make sure already cacheable (fresh) responses from eZ Platform which are errors/redirect gets lower ttl (then default_ttl)
            -   match:
                    match_response: "response.isFresh() && ( response.isServerError() || response.isClientError() || response.isRedirect() )"
                headers:
                    overwrite: true
                    cache_control:
                        max_age: 5
                        s_maxage: 20
            # Example of performance tuning, force TTL on 404 pages to avoid crawlers / ... taking to much load
            # Should not be set to high, as cached 404's can cause issues for future routes, url aliases, wildcards, ..
            -   match:
                    match_response: "!response.isFresh() && response.isNotFound()"
                headers:
                    overwrite: true
                    cache_control:
                        public: true
                        max_age: 0
                        s_maxage: 20
